name: WakaTime Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 19 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@413150be53d5559a8e125ce81145026f086bfb8d
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
